spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  ai:
    openai:
      api-key: ${AI_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRE}

aws:
  s3:
    bucket: ${AWS_BUCKET}
    domain: ${AWS_BUCKET_URL}
  cloudfront:
    domain: ${CLOUDFRONT_URL}
